version: '3'

volumes:
    jenkins-home:

services:
    vault:
      image: vault
      cap_add:
        - IPC_LOCK
      ports:
        - 8200:8200

    jenkins-master:
      image: lucksolutions/jenkins-master
      volumes:
        - jenkins-home:/var/jenkins_home
      ports:
        - 80:8080

      